/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCatalogRouteImport } from './routes/app/catalog'
import { Route as AppMapRouteImport } from './routes/app/map'
import { Route as AppMistakesRouteImport } from './routes/app/mistakes'
import { Route as AppParentRouteImport } from './routes/app/parent'
import { Route as AppStampsRouteImport } from './routes/app/stamps'
import { Route as AppWorkshopRouteImport } from './routes/app/workshop'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoCatalogRouteImport } from './routes/demo/catalog'
import { Route as DemoMapRouteImport } from './routes/demo/map'
import { Route as DemoMistakesRouteImport } from './routes/demo/mistakes'
import { Route as DemoParentRouteImport } from './routes/demo/parent'
import { Route as DemoStampsRouteImport } from './routes/demo/stamps'
import { Route as DemoWorkshopRouteImport } from './routes/demo/workshop'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppKanjiCharRouteImport } from './routes/app/kanji.$char'
import { Route as DemoKanjiCharRouteImport } from './routes/demo/kanji.$char'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMistakesRoute = AppMistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppParentRoute = AppParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStampsRoute = AppStampsRouteImport.update({
  id: '/stamps',
  path: '/stamps',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppWorkshopRoute = AppWorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => AppRouteRoute,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCatalogRoute = DemoCatalogRouteImport.update({
  id: '/demo/catalog',
  path: '/demo/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMapRoute = DemoMapRouteImport.update({
  id: '/demo/map',
  path: '/demo/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMistakesRoute = DemoMistakesRouteImport.update({
  id: '/demo/mistakes',
  path: '/demo/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoParentRoute = DemoParentRouteImport.update({
  id: '/demo/parent',
  path: '/demo/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStampsRoute = DemoStampsRouteImport.update({
  id: '/demo/stamps',
  path: '/demo/stamps',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoWorkshopRoute = DemoWorkshopRouteImport.update({
  id: '/demo/workshop',
  path: '/demo/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppKanjiCharRoute = AppKanjiCharRouteImport.update({
  id: '/kanji/$char',
  path: '/kanji/$char',
  getParentRoute: () => AppRouteRoute,
} as any)
const DemoKanjiCharRoute = DemoKanjiCharRouteImport.update({
  id: '/demo/kanji/$char',
  path: '/demo/kanji/$char',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/parents': typeof ParentsRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/map': typeof AppMapRoute
  '/app/mistakes': typeof AppMistakesRoute
  '/app/parent': typeof AppParentRoute
  '/app/stamps': typeof AppStampsRoute
  '/app/workshop': typeof AppWorkshopRoute
  '/demo/catalog': typeof DemoCatalogRoute
  '/demo/map': typeof DemoMapRoute
  '/demo/mistakes': typeof DemoMistakesRoute
  '/demo/parent': typeof DemoParentRoute
  '/demo/stamps': typeof DemoStampsRoute
  '/demo/workshop': typeof DemoWorkshopRoute
  '/app/': typeof AppIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/kanji/$char': typeof AppKanjiCharRoute
  '/demo/kanji/$char': typeof DemoKanjiCharRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/parents': typeof ParentsRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/map': typeof AppMapRoute
  '/app/mistakes': typeof AppMistakesRoute
  '/app/parent': typeof AppParentRoute
  '/app/stamps': typeof AppStampsRoute
  '/app/workshop': typeof AppWorkshopRoute
  '/demo/catalog': typeof DemoCatalogRoute
  '/demo/map': typeof DemoMapRoute
  '/demo/mistakes': typeof DemoMistakesRoute
  '/demo/parent': typeof DemoParentRoute
  '/demo/stamps': typeof DemoStampsRoute
  '/demo/workshop': typeof DemoWorkshopRoute
  '/app': typeof AppIndexRoute
  '/demo': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/kanji/$char': typeof AppKanjiCharRoute
  '/demo/kanji/$char': typeof DemoKanjiCharRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/parents': typeof ParentsRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/map': typeof AppMapRoute
  '/app/mistakes': typeof AppMistakesRoute
  '/app/parent': typeof AppParentRoute
  '/app/stamps': typeof AppStampsRoute
  '/app/workshop': typeof AppWorkshopRoute
  '/demo/catalog': typeof DemoCatalogRoute
  '/demo/map': typeof DemoMapRoute
  '/demo/mistakes': typeof DemoMistakesRoute
  '/demo/parent': typeof DemoParentRoute
  '/demo/stamps': typeof DemoStampsRoute
  '/demo/workshop': typeof DemoWorkshopRoute
  '/app/': typeof AppIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/kanji/$char': typeof AppKanjiCharRoute
  '/demo/kanji/$char': typeof DemoKanjiCharRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboard'
    | '/parents'
    | '/app/catalog'
    | '/app/map'
    | '/app/mistakes'
    | '/app/parent'
    | '/app/stamps'
    | '/app/workshop'
    | '/demo/catalog'
    | '/demo/map'
    | '/demo/mistakes'
    | '/demo/parent'
    | '/demo/stamps'
    | '/demo/workshop'
    | '/app/'
    | '/demo/'
    | '/api/auth/$'
    | '/app/kanji/$char'
    | '/demo/kanji/$char'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboard'
    | '/parents'
    | '/app/catalog'
    | '/app/map'
    | '/app/mistakes'
    | '/app/parent'
    | '/app/stamps'
    | '/app/workshop'
    | '/demo/catalog'
    | '/demo/map'
    | '/demo/mistakes'
    | '/demo/parent'
    | '/demo/stamps'
    | '/demo/workshop'
    | '/app'
    | '/demo'
    | '/api/auth/$'
    | '/app/kanji/$char'
    | '/demo/kanji/$char'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboard'
    | '/parents'
    | '/app/catalog'
    | '/app/map'
    | '/app/mistakes'
    | '/app/parent'
    | '/app/stamps'
    | '/app/workshop'
    | '/demo/catalog'
    | '/demo/map'
    | '/demo/mistakes'
    | '/demo/parent'
    | '/demo/stamps'
    | '/demo/workshop'
    | '/app/'
    | '/demo/'
    | '/api/auth/$'
    | '/app/kanji/$char'
    | '/demo/kanji/$char'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  ParentsRoute: typeof ParentsRoute
  DemoCatalogRoute: typeof DemoCatalogRoute
  DemoMapRoute: typeof DemoMapRoute
  DemoMistakesRoute: typeof DemoMistakesRoute
  DemoParentRoute: typeof DemoParentRoute
  DemoStampsRoute: typeof DemoStampsRoute
  DemoWorkshopRoute: typeof DemoWorkshopRoute
  DemoIndexRoute: typeof DemoIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoKanjiCharRoute: typeof DemoKanjiCharRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/catalog': {
      id: '/app/catalog'
      path: '/catalog'
      fullPath: '/app/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/mistakes': {
      id: '/app/mistakes'
      path: '/mistakes'
      fullPath: '/app/mistakes'
      preLoaderRoute: typeof AppMistakesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/parent': {
      id: '/app/parent'
      path: '/parent'
      fullPath: '/app/parent'
      preLoaderRoute: typeof AppParentRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/stamps': {
      id: '/app/stamps'
      path: '/stamps'
      fullPath: '/app/stamps'
      preLoaderRoute: typeof AppStampsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/workshop': {
      id: '/app/workshop'
      path: '/workshop'
      fullPath: '/app/workshop'
      preLoaderRoute: typeof AppWorkshopRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/catalog': {
      id: '/demo/catalog'
      path: '/demo/catalog'
      fullPath: '/demo/catalog'
      preLoaderRoute: typeof DemoCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/map': {
      id: '/demo/map'
      path: '/demo/map'
      fullPath: '/demo/map'
      preLoaderRoute: typeof DemoMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mistakes': {
      id: '/demo/mistakes'
      path: '/demo/mistakes'
      fullPath: '/demo/mistakes'
      preLoaderRoute: typeof DemoMistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/parent': {
      id: '/demo/parent'
      path: '/demo/parent'
      fullPath: '/demo/parent'
      preLoaderRoute: typeof DemoParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/stamps': {
      id: '/demo/stamps'
      path: '/demo/stamps'
      fullPath: '/demo/stamps'
      preLoaderRoute: typeof DemoStampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/workshop': {
      id: '/demo/workshop'
      path: '/demo/workshop'
      fullPath: '/demo/workshop'
      preLoaderRoute: typeof DemoWorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/kanji/$char': {
      id: '/app/kanji/$char'
      path: '/kanji/$char'
      fullPath: '/app/kanji/$char'
      preLoaderRoute: typeof AppKanjiCharRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/demo/kanji/$char': {
      id: '/demo/kanji/$char'
      path: '/demo/kanji/$char'
      fullPath: '/demo/kanji/$char'
      preLoaderRoute: typeof DemoKanjiCharRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppCatalogRoute: typeof AppCatalogRoute
  AppMapRoute: typeof AppMapRoute
  AppMistakesRoute: typeof AppMistakesRoute
  AppParentRoute: typeof AppParentRoute
  AppStampsRoute: typeof AppStampsRoute
  AppWorkshopRoute: typeof AppWorkshopRoute
  AppIndexRoute: typeof AppIndexRoute
  AppKanjiCharRoute: typeof AppKanjiCharRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCatalogRoute: AppCatalogRoute,
  AppMapRoute: AppMapRoute,
  AppMistakesRoute: AppMistakesRoute,
  AppParentRoute: AppParentRoute,
  AppStampsRoute: AppStampsRoute,
  AppWorkshopRoute: AppWorkshopRoute,
  AppIndexRoute: AppIndexRoute,
  AppKanjiCharRoute: AppKanjiCharRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  ParentsRoute: ParentsRoute,
  DemoCatalogRoute: DemoCatalogRoute,
  DemoMapRoute: DemoMapRoute,
  DemoMistakesRoute: DemoMistakesRoute,
  DemoParentRoute: DemoParentRoute,
  DemoStampsRoute: DemoStampsRoute,
  DemoWorkshopRoute: DemoWorkshopRoute,
  DemoIndexRoute: DemoIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoKanjiCharRoute: DemoKanjiCharRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
